clc ;
close ;
a = imread ("C:\Users\prath\Desktop");
k = 255 - double (a);
k = uint8 (k);
figure(1);
imshow (uint8(a));
title ( 'Original Image' );
figure(2);
imshow (k);
title ( 'Negative of Original Image' );
