img = imread("D:\\Picture1.png");
img=rgb2gray(img);
c=edge(img,'sobel',0.5)
d=edge(img,'prewitt')
e=edge(img,'canny')
f=edge(img,'log')
figure(1)
imshow(img)
title('Original Image')
figure(2)
imshow(c)
title('Sobel')
figure(3)
imshow(d)
title('Prewitt')
figure(4)
imshow(e)
title('Canny')
figure(5)
imshow(f)
title('LOG')
